-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2018-04-10 17:05:58.662

-- foreign keys
ALTER TABLE APPLICATION
    DROP CONSTRAINT APPLICATION_JOBS;

ALTER TABLE APPLICATION
    DROP CONSTRAINT APPLICATION_RESUMES;

ALTER TABLE EMPLOYERS
    DROP CONSTRAINT EMPLOYERS_INDUSTRY;

ALTER TABLE EMPLOYERS
    DROP CONSTRAINT EMPLOYERS_STATES;

ALTER TABLE JOBS
    DROP CONSTRAINT JOBS_AGENCY;

ALTER TABLE JOBS
    DROP CONSTRAINT JOBS_EMPLOYERS;

ALTER TABLE RESUMES
    DROP CONSTRAINT RESUMES_STUDENTS;

-- tables
DROP TABLE APPLICATION;

DROP TABLE EMPLOYERS;

DROP TABLE INDUSTRY;

DROP TABLE JOBS;

DROP TABLE RECRUITER;

DROP TABLE RESUMES;

DROP TABLE STATES;

DROP TABLE STUDENTS;

-- End of file.

